name: 'Setup Python'
description: 'Set up a specific version of Python and add the command-line tools to the PATH'
author: 'GitHub'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'yellow'
