name: Monitoring

on: 
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ./
      env:
        owner: "kubernetes"
        repo: "website"
        offset_hours: 1
        prefix: "content/en"
        secrets: ${{ secrets.incoming_webhooks }}
        
