name: Monitoring
on: [push]
# on: 
#   schedule:
#     - cron:  '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shinhwagk/monitoring_document@master
      env:
        owner: "kubernetes"
        repo: "website"
        offset_hours: 20
        prefix: "content/en"
        secrets: ${{ secrets.incoming_webhooks }}
        
